# Generated by Django 4.1.7 on 2023-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_section_teacherid_delete_departmentbatchsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.IntegerField(),
        ),
    ]
