# Generated by Django 4.1.7 on 2023-05-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_section_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='teacherid',
            options={'verbose_name': 'Teacher_ID', 'verbose_name_plural': 'Teacher_id'},
        ),
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
            options={
                'verbose_name': 'Student_ID',
                'verbose_name_plural': 'Student_ID',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('semesterName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.semestername')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacherid')),
            ],
            options={
                'verbose_name': 'Semeter',
                'verbose_name_plural': 'Semester',
            },
        ),
    ]
