# Generated by Django 4.1.7 on 2023-05-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sessiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
    ]
