# Generated by Django 4.1.7 on 2023-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_semester_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semesterName',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='teacherId',
        ),
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SemesterName',
        ),
    ]
