# Generated by Django 4.1.7 on 2023-05-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_semester_options_remove_semester_semestername_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherId',
        ),
    ]
