# Generated by Django 4.1.7 on 2023-05-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_teacherid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionData',
        ),
    ]
