# Generated by Django 4.1.7 on 2023-05-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sessiondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year']},
        ),
    ]
