# Generated by Django 4.1.7 on 2023-05-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_filedatabase_alter_postdb_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileDatabase',
        ),
    ]
