# Generated by Django 4.1.7 on 2023-05-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_filedatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='uploadFile',
        ),
    ]
