# Generated by Django 4.1.7 on 2023-05-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_teacherprofile_cover_pic_teacherprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentId',
        ),
    ]
