# Generated by Django 4.1.7 on 2023-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_coverPic/'),
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_profilePic/'),
        ),
        migrations.AddField(
            model_name='studentsprofile',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
