# Generated by Django 4.1.7 on 2023-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_studentsprofile_address_studentsprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondata',
            name='token',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
