# Generated by Django 4.1.7 on 2023-06-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_sessiondata_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentsprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sessiondata')),
            ],
            options={
                'verbose_name': 'Session Member',
                'verbose_name_plural': 'Session Member',
            },
        ),
    ]
