# Generated by Django 4.1.7 on 2023-06-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_filedatabase_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic', null=True, upload_to='student_profilePic/'),
        ),
    ]
