# Generated by Django 4.1.7 on 2023-06-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_studentsprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.webp', null=True, upload_to='student_profilePic/'),
        ),
    ]
