# Generated by Django 4.1.7 on 2023-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_studentsprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='has_file',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
